apiVersion: v1
kind: ConfigMap
metadata:
  name: es9-config
data:
  elasticsearch.yml: |
    cluster.name: es9-operator-e2e
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.seed_hosts: [es9-master]
    cluster.initial_master_nodes: [es9-master-0]
    cluster.no_master_block: "write"
    gateway.expected_data_nodes: 0
    indices.breaker.total.use_real_memory: false
    indices.lifecycle.history_index_enabled: false
    slm.history_index_enabled: false
    
    # Disable X-Pack features
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.ml.enabled: false
    xpack.watcher.enabled: false
    xpack.graph.enabled: false
    xpack.ccr.enabled: false

    # Disable EQL
    xpack.eql.enabled: false
